server:
  port: 9999

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false # 본 서버는 유레카 디스커버리 서버이므로 자신을 클라언트로 등록하지 않는 설정입니다.
    fetch-registry: false # 유레카 디스크커버리 서버에서 리스트 정보를 로컬에 caching 할지 여부입니다. 본 서바가 유레카 디스커버리 서버이므로 비활성화합니다.
  serviceUrl:
    defaultZone: http://52.79.162.165:9999
  #server:
  #  waitTimeInMsWhenSyncEmpty: 5 # 5ms만에 등록한 서비스를 알리도록 설정. 테스트 용도. 운영 환경에서는 주석처리.
  #  #유레카는 서비스가 등록되면 10초 간격으로 연속 3회 동안 상태정보를 받고 최종 등록하므로 서비스를 보여주는데 30초 걸림
